import Vue from 'vue';
import VueRouter from 'vue-router';

import "../src/styles/index.scss";
// import "./components/IVueButton.test";
// import "./components/IVueIcon.test";
// import "./components/IVueList.test";
// import "./components/IVueListItem.test";
// import "./components/IVueSpin.test";
// import "./components/IVueCarousel.test";
// import "./components/IVueSwitch.test";
// import "./components/IVueBottomNav.test";
// import "./components/IVueBreadcrumbs.test";
// import "./components/IVueSelect.test";
// import "./components/IVueAutoComplete.test";
// import "./components/IVueInput.test";
// import "./components/IVueStepper.test";
// import "./components/IVueUpLoad.test";
// import "./components/IVueProgress.test";
// import "./components/IVueNotice.test";
// import "./components/IVueMessage.test";
// import "./components/IVueTabs.test";
// import "./components/IVueLoadingBar.test";
import "./components/IVueBadge.test";
