import './util/CreateNativeLocaleFormatter.test';
import './util/MonthChange.test';
import './util/Pad.test';
import './IvueDatePicker.date.test';
import './IvueDatePicker.month.test';
import './IvueDatePickerDateTable.test'
import './IvueDatePickerHeader.test';
import './IvueDatePickerMonth.test';
import './IvueDatePickerTitle.test';
import './IvueDatePickerYears.test';
