import './util/CreateNativeLocaleFormatter.test';
import './util/MonthChange.test';
import './util/Pad.test';
import './IVueDatePicker.date.test';
import './IVueDatePicker.month.test';
import './IVueDatePickerDateTable.test'
import './IVueDatePickerHeader.test';
import './IVueDatePickerMonth.test';
import './IVueDatePickerTitle.test';
import './IVueDatePickerYears.test';
